name: Memory Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  valgrind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y valgrind libgl1-mesa-dev xorg-dev

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Debug -DMVN_BUILD_TESTS=ON -DMVN_TEST_CI=ON

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config Debug

      - name: Run tests with Valgrind
        working-directory: ${{github.workspace}}/build/tests
        run: |
          valgrind --leak-check=full --error-exitcode=1 ./mvn_test_all
